[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.build]
cmds = ['npm install', 'npx turbo run build']

[phases.deploy]
cmd = 'turbo run start --filter=home-appliance-backend'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'