[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "."
build.buildCommand = "npm install && npm run build"
build.watchPatterns = ["src/**"]

[[services]]
name = "backend"
source = "./backend"
build.buildCommand = "npm install && npm run build"
build.watchPatterns = ["src/**"]
variables.NODE_ENV = "production"