[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.build]
cmds = ['npm install', 'npm run build']

[phases.deploy]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[start]
cmd = 'npm start'